### ISSUE TITLE
TypeError: create_model() missing 1 required positional argument: 'css'

### ISSUE THREAD

**Issue by hoonlight** [TRIAEIOU/flexible-cloze-2#5]
Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.3.1-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-05-03 22:06:22
Flexible cloze 2⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 217, in on_window_init
  File "aqt.main", line 316, in setupProfile
  File "aqt.main", line 496, in loadProfile
  File "_aqt.hooks", line 3809, in __call__
  File "/Users/hoon/Library/Application Support/Anki2/addons21/1889069832/__init__.py", line 135, in update
    create_model(mw.col, nfront, nback, ncss)
TypeError: create_model() missing 1 required positional argument: 'css'

**Comment by comienzo2093** [comment]
[1a32135](https://github.com/TRIAEIOU/flexible-cloze-2/pull/6/commits/1a321358ca730d302b6ca2dca1d02cbebda82e4f)

**Comment by hoonlight** [comment]
#6
